import {icon} from './icons.js';
import {capabilities,industries,technologies,process,engagements} from './content.js';
import {network,industryArt} from './art.js';
import {documentPage,serviceUrl,industryUrl} from './site-layout.js';
const cta=()=>`<section class="page-cta wrap section"><div><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>Let’s make<br><em>progress together.</em></h2></div><a class="button primary" href="/contact.html">Plan your project ${icon('north_east')}</a></section>`;
const hero=(eyebrow,title,copy,art=network(0))=>`<section class="page-hero wrap"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span>${eyebrow.startsWith('Services / ')?`<a href="/services.html">Services</a><span aria-hidden="true">/</span><span>${eyebrow.slice(11)}</span>`:eyebrow.startsWith('Industries / ')?`<a href="/industries.html">Industries</a><span aria-hidden="true">/</span><span>${eyebrow.slice(13)}</span>`:`<span>${eyebrow}</span>`}</nav><div class="page-hero-grid"><div><span class="eyebrow">${eyebrow.toUpperCase()}</span><h1>${title}</h1><p>${copy}</p><a class="text-link" href="#details">Explore the details ${icon('arrow_downward')}</a></div><div class="page-art">${art}<span class="eyebrow">CRAFTERTECH / CONNECTED ENGINEERING</span></div></div></section>`;
const cards=(items)=>`<div class="page-cards">${items.map((c,i)=>`<article class="page-card"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${c.title}</h3><p>${c.text}</p>${c.url?`<a class="${c.highlight?'text-link collection-link':'text-link'}" href="${c.url}">Explore ${c.short||'service'} ${icon('north_east')}</a>`:''}</article>`).join('')}</div>`;
const section=(title,content)=>`<section id="details" class="wrap section page-details"><h2>${title}</h2>${content}</section>`;
const steps=(items)=>`<ol class="delivery-steps">${items.map((p,i)=>`<li><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${p.name}</h3><p>${p.text}</p></li>`).join('')}</ol>`;
const faq=(items)=>`<section class="wrap section page-faq"><h2>A few useful answers.</h2>${items.map(([q,a])=>`<details><summary>${q}${icon('add')}</summary><p>${a}</p></details>`).join('')}</section>`;
const serviceDetails=[
 [['AI readiness & strategy','Identify the workflow, assess data readiness and define a practical evaluation plan before selecting a model.'],['Knowledge & retrieval','Connect documents and business systems to retrieval pipelines that keep answers grounded in relevant information.'],['Intelligent workflows','Combine models, tools and human review to assist teams with repeatable, information-heavy tasks.']],
 [['Product discovery','Translate user needs and operational constraints into a clear product scope and architecture.'],['Web, mobile & APIs','Build connected interfaces and services, with reusable components and documented integration boundaries.'],['Application modernization','Improve legacy systems incrementally through API integration, migration planning and tested releases.']],
 [['Cloud foundations','Define environments, access boundaries and infrastructure patterns around workload requirements.'],['Migration & modernization','Inventory dependencies, plan migration stages and validate behavior before moving critical workloads.'],['DevOps & operations','Use infrastructure as code, repeatable pipelines and observability to make releases easier to operate.']],
 [['Data integration','Connect source systems through pipelines with clear ownership, quality checks and recoverable processing.'],['Analytics & reporting','Define useful metrics and build reporting experiences that give teams consistent business context.'],['Data for AI','Prepare governed datasets and retrieval infrastructure, with lineage and access controls across the lifecycle.']],
 [['Quality strategy','Identify high-risk journeys and define coverage across functional, integration and performance testing.'],['Test automation','Automate repeatable checks and integrate reliable feedback into the delivery pipeline.'],['Release confidence','Use clear acceptance criteria, defect triage and release evidence to support informed launch decisions.']],
 [['Secure architecture','Review trust boundaries, identity, data flows and threat scenarios before implementation.'],['Identity & protection','Design access controls, encryption and monitoring around the sensitivity of each system.'],['Ongoing assurance','Build security checks into delivery and establish review, incident response and remediation processes.']]
];
export function pages(){const result=new Map();const add=(path,title,copy,body)=>result.set(path,documentPage(title,copy,body,path));
 add('/services.html','Services','Connected engineering across AI, software, cloud, data, quality and security.',hero('Services','Every layer.<br><em>One engineering partner.</em>','Connect the intelligence in your applications to the systems beneath them. Explore six complementary engineering disciplines.')+section('Engineering, connected.',cards(capabilities.map((c,i)=>({title:c.title,text:c.description,url:serviceUrl(i),short:c.short,highlight:true}))))+cta());
 capabilities.forEach((c,i)=>{const scope=serviceDetails[i];add(serviceUrl(i),c.title,c.description,hero('Services / '+c.short,c.title,c.description,network(i))+section('Built around the work.',cards(scope.map(([title,text])=>({title,text}))))+`<section class="page-band dark-section"><div class="wrap"><span class="eyebrow">THE BUSINESS OBJECTIVE</span><h2>${c.impact}</h2><div class="tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></section><section class="wrap section"><h2>From context to delivery.</h2>${steps([{name:'Understand',text:'Map the existing environment, users and constraints. Agree on the problem and a measurable definition of progress.'},{name:'Build & validate',text:'Deliver a focused scope in stages. Review quality, security and business fit with the people who will use it.'},{name:'Operate & improve',text:'Prepare documentation, monitoring and ownership. Use feedback from real workflows to prioritize the next release.'}])}</section>`+faq([['Where do we start?','Start with a specific workflow or system. Share its users, current limitations, available data and the outcome you want to improve.'],['Can you work with existing systems?','The approach begins with a review of your architecture and dependencies. Integration and phased modernization can be considered alongside new development.'],['How is delivery scoped?','Scope, milestones and acceptance criteria are agreed after discovery. The plan should reflect your team, infrastructure and operational constraints.']])+cta());});
 add('/industries.html','Industries','Engineering shaped around the workflows and constraints of your industry.',hero('Industries','Context changes everything.','Every industry has its own systems, terminology and operational requirements. Start with your domain, then connect the engineering it needs.',industryArt(0))+section('Find your industry.',cards(industries.map((v,i)=>({title:v.name,text:v.text,url:industryUrl(i),short:v.name,highlight:true}))))+cta());
 industries.forEach((v,i)=>add(industryUrl(i),v.name,v.text,hero('Industries / '+v.name,v.title.replace('\n','<br>'),v.text,industryArt(i))+section('Where technology can help.',cards(v.tags.map((t,j)=>({title:t,text:[`Map the ${t.toLowerCase()} workflow, its users and the information they need. Design the experience around real operational decisions.`,`Connect ${t.toLowerCase()} with existing systems through clear integration contracts and access controls.`,`Introduce ${t.toLowerCase()} in a focused scope, validate it with users and measure the effect before expanding.`][j]}))))+`<section class="page-band dark-section"><div class="wrap"><span class="eyebrow">DOMAIN CONTEXT / ENGINEERING DISCIPLINE</span><h2>Built for the way<br>your teams work.</h2><p>Begin with user journeys, data flows and operational constraints. Review relevant privacy, security and governance requirements during discovery and carry them through architecture, testing and delivery.</p></div></section><section class="wrap section"><h2>A connected delivery team.</h2>${cards([0,1,3].map(k=>({title:capabilities[k].title,text:capabilities[k].impact,url:serviceUrl(k),short:capabilities[k].short})))}</section>`+cta()));
 add('/technology.html','Technology','An open technology ecosystem selected around your business needs.',hero('Technology','The right tools.<br><em>For the right reasons.</em>','Select platforms around your existing environment, integration needs and operating model. Explore the technologies across our engineering disciplines.',network(2))+section('An open ecosystem.',`<div class="technology-directory">${technologies.map(t=>`<article><h3>${t.name}</h3><div><p>${t.text}</p><div class="tags">${t.items.map(x=>`<span>${x}</span>`).join('')}</div></div></article>`).join('')}</div>`)+cta());
 add('/about.html','About Craftertech','Business-led engineering across the enterprise technology lifecycle.',hero('About Craftertech','Curious minds.<br><em>Connected expertise.</em>','Craftertech brings AI, software, cloud, data, quality and security into one engineering conversation. We start with the business context and build around the people doing the work.',network(1))+section('How we think.',cards([{title:'Start with purpose.',text:'Understand the decision, workflow or experience that needs to improve. Define success before choosing the technology.'},{title:'Build with care.',text:'Consider security, maintainability and accessibility throughout design and delivery. Make tradeoffs visible and decisions understandable.'},{title:'Work as one team.',text:'Share context, review progress together and build a delivery rhythm that gives everyone a clear view of the next step.'}]))+`<section class="page-band dark-section"><div class="wrap"><h2>Depth across disciplines.<br>Clarity across delivery.</h2><p>A useful engineering partnership connects strategy with execution. Our approach brings the right disciplines together from discovery through operation.</p><a class="text-link" href="/approach.html">Explore our approach ${icon('north_east')}</a></div></section>`+cta());
 add('/approach.html','Our Approach','A considered path from business context to working software.',hero('Our approach','Clear priorities.<br><em>Considered delivery.</em>','A shared understanding of the problem, a practical architecture and visible progress. Build confidence at each stage before moving to the next.',network(4))+section('From the first question to scale.',steps(process))+`<section class="wrap section"><h2>A partnership that fits.</h2>${cards(engagements.map(e=>({title:e.name,text:e.text+' '+e.fit})))}</section>`+faq([['How do we measure progress?','Agree on baseline measures and acceptance criteria during discovery. Review delivery milestones and the effect on the intended workflow.'],['What does handover include?','Define documentation, access, operational ownership, monitoring and support expectations as part of the delivery scope.']])+cta());
 const projects=[{title:'Legal document intelligence',text:'A reference pattern for turning complex documents into searchable knowledge through parsing, conversational research and page-level citations.',challenge:'Legal teams need to find relevant information across large, complex documents.',approach:'Combine document ingestion, retrieval and a conversational interface that carries source context into each answer.',tags:['Document intelligence','Retrieval','Citations']},{title:'Connected health benefits',text:'A reference pattern for modernizing a legacy benefits platform into connected enterprise workflows.',challenge:'Disconnected desktop tools make it harder to coordinate claims and benefits information.',approach:'Model the end-to-end lifecycle, expose integrations through APIs and build role-based web experiences.',tags:['Enterprise applications','Workflow integration','Modernization']},{title:'Digital public administration',text:'A reference pattern for centralizing registration, administration and reporting workflows.',challenge:'Separate operational systems create repeated entry and fragmented reporting.',approach:'Connect registration and administration through shared data structures, controlled access and traceable operational events.',tags:['Public sector','Secure systems','Reporting']}];
 add('/work.html','Project References','Explore engineering reference patterns for document intelligence, enterprise modernization and public services.',hero('Project references','From complexity<br><em>to working systems.</em>','Explore engineering patterns drawn from published third-party examples. These are reference scenarios, not claims of Craftertech client engagements.',network(3))+section('Engineering in practice.',`<div class="reference-stories">${projects.map((p,i)=>`<article><div class="reference-art">${network(i+1)}</div><div><span class="eyebrow">REFERENCE ${String(i+1).padStart(2,'0')}</span><h2>${p.title}</h2><p>${p.text}</p><details><summary>Explore the engineering ${icon('add')}</summary><h3>The challenge</h3><p>${p.challenge}</p><h3>The approach</h3><p>${p.approach}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></details></div></article>`).join('')}</div>`)+cta());
 add('/contact.html','Contact','Prepare a project brief for a conversation with Craftertech.',hero('Contact','What would you<br><em>like to build?</em>','Start with the challenge, the people it affects and the outcome you want. Use the brief builder below to organize your ideas.',network(0))+section('Prepare your project brief.',`<div class="contact-grid"><div><h3>A useful first conversation.</h3><p>Describe the current workflow, where it falls short and the change you want to make. Existing systems, data access and timing help shape a practical starting point.</p><p class="contact-pending">Direct contact details will be added here when available. This tool downloads your brief to your device; it does not send an inquiry.</p></div><form id="project-brief"><label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Work email<input name="email" type="email" autocomplete="email" required maxlength="200"></label><label>Area of interest<select name="service">${capabilities.map(c=>`<option>${c.title}</option>`).join('')}<option>Help me define the scope</option></select></label><label>What are you looking to achieve?<textarea name="goals" rows="5" required maxlength="5000"></textarea></label><label>Target timeline<input name="timeline" placeholder="For example, explore a pilot this quarter" maxlength="200"></label><button class="button primary" type="submit">Download project brief ${icon('arrow_downward')}</button><p id="brief-status" role="status"></p></form></div>`));
 return result;}
