import {domainSection} from './domain.js';
import {intelligenceSection} from './intelligence.js';
import {icon} from './icons.js';
import {header,footer,serviceUrl} from './site-layout.js';
import { capabilities, process, technologies, challenges, outcomes, engagements } from './content.js';
import { sculpture, network, industryArt } from './art.js';
const arrow=icon('arrow_forward');
const diagonal=icon('north_east');
const plus=icon('add','plus');
const n=i=>String(i+1).padStart(2,'0');
const tags=items=>`<div class="tags">${items.map(x=>`<span>${x}</span>`).join('')}</div>`;
const expertisePhotos=[
 ['ai','Humanoid robot demonstrating real-world artificial intelligence'],
 ['applications','Laptop displaying application source code on a developer’s desk'],
 ['cloud','Rows of server racks supporting cloud infrastructure'],
 ['data','Analytics dashboard with charts and business performance metrics'],
 ['quality','Colleagues reviewing software together on a laptop'],
 ['security','Padlock on a keyboard representing secure access to digital systems'],
];
const label=(num,text)=>`<div class="section-label"><span class="tiny-mark" aria-hidden="true"></span><span>${text}</span><span class="section-number">${num} / 12</span></div>`;
const heading=(title,copy='')=>`<div class="section-heading"><h2>${title}</h2>${copy?`<p>${copy}</p>`:''}</div>`;
const wordmark=(tone="black")=>`<img class="brand-symbol" src="/assets/craftertech-${tone}.svg" width="34" height="34" alt=""><span>craftertech</span>`;

export function render(){return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f4f7fc"><title>Craftertech — Enterprise AI & Software Engineering</title><meta name="description" content="Enterprise AI, software, cloud and data engineering. Explore Craftertech’s capabilities across AI, software, cloud, data and security."><meta property="og:title" content="Craftertech — Enterprise AI. Engineered for your business."><meta property="og:description" content="Connected expertise in AI, applications, cloud, data and security. Engineering for your business."><meta property="og:type" content="website"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/instrument-sans-regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="/vendor/lenis.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/typography.css"><link rel="stylesheet" href="/pages.css"><link rel="stylesheet" href="/intelligence.css"><link rel="stylesheet" href="/domain.css"><script type="module" src="/client.js"></script></head>
<body id="top"><a class="skip-link" href="#main">Skip to content</a>
${header()}
<main id="main" tabindex="-1">
<section class="hero wrap" aria-labelledby="hero-title"><div class="hero-top"><span class="eyebrow"><span class="status-dot"></span>ENTERPRISE AI & SOFTWARE ENGINEERING</span><span class="hero-edition eyebrow">BUILT ON DEPTH. DRIVEN BY INTELLIGENCE.</span></div><div class="hero-grid"><div class="hero-copy"><h1 id="hero-title">Enterprise AI.<br>Engineered for<br><em>your business.</em></h1><p>Bring AI into your workflows with the software,<br class="desktop-break"> data and cloud engineering to support it.</p><div class="hero-actions"><a class="button primary" href="/contact.html">Let’s build what’s next ${arrow}</a><a class="text-link" href="#work">Explore project examples ${diagonal}</a></div></div><div class="hero-art"><span class="art-cross top-left" aria-hidden="true">+</span><span class="art-cross bottom-right" aria-hidden="true">+</span>${sculpture()}<div class="art-caption"><span class="mini-line"></span>CONNECTED EXPERTISE.<br>COMPOUNDING POSSIBILITIES.</div><span class="art-coordinate" aria-hidden="true">[ 01 — ∞ ]</span></div></div><div class="hero-bottom"><span>STRATEGY TO SYSTEMS. CONCEPT TO SCALE.</span><a href="#expertise">Discover the depth behind the intelligence ${icon('arrow_downward')}</a></div></section>

<section id="expertise" class="expertise wrap section">${label('02','THE DEPTH BEHIND THE WORK')}<div class="expertise-grid"><div class="big-stat">06<small>CONNECTED ENGINEERING DISCIPLINES</small></div><div class="expertise-copy"><h2>New possibilities.<br>Deep foundations.</h2><p>AI works best with strong foundations. We connect software, cloud, data, quality and security to bring intelligence into your business.</p><a class="text-link" href="/about.html">Meet Craftertech ${diagonal}</a></div></div><div class="stack-band">${['AI','APPLICATIONS','CLOUD','DATA','SECURITY'].map((s,i)=>`<span><small>${n(i)}</small>${s}${i<4?'<b aria-hidden="true">+</b>':''}</span>`).join('')}</div></section>

<section id="capabilities" class="capabilities wrap section">${label('03','CONNECTED CAPABILITIES')}${heading('Every layer.<br>One engineering partner.','From the intelligence in your applications to the infrastructure beneath them, we connect the disciplines that make transformation work.')}<div class="cap-layout"><aside class="cap-index"><span class="eyebrow">EXPLORE OUR EXPERTISE</span><nav aria-label="Capability index">${capabilities.map((c,i)=>`<a href="#cap-${i}" ${i===0?'aria-current="true"':''}><span>${n(i)}</span>${c.short}${arrow}</a>`).join('')}</nav><div class="cap-index-note"><span class="tiny-mark" aria-hidden="true"></span>Engineered to work together.</div></aside><div class="cap-stories">${capabilities.map((c,i)=>`<details id="cap-${i}" class="cap-story" open><summary><span class="eyebrow">${n(i)} / ENGINEERING CAPABILITIES</span><h3>${c.title}</h3>${plus}</summary><div class="cap-body"><p>${c.description}</p><div class="cap-visual cap-photo"><img src="/assets/expertise/${expertisePhotos[i][0]}.jpg" alt="${expertisePhotos[i][1]}" width="1200" height="720" loading="lazy" decoding="async"><div class="diagram-caption">${c.flow.map(t=>`<span>${t}</span>`).join('<b aria-hidden="true">→</b>')}</div></div>${tags(c.tags)}<p class="impact"><span>THE BUSINESS IMPACT</span>${c.impact}</p><a class="text-link" href="${serviceUrl(i)}">Explore this service ${diagonal}</a></div></details>`).join('')}</div></div></section>

${intelligenceSection()}

<section id="process" class="process-section process-depth section"><div class="wrap">${label('05','A CONSIDERED PATH FORWARD')}${heading('From the right question<br>to the right solution.')}<div data-tabs="process" class="process-depth-system"><div role="tablist" aria-label="AI transformation process" aria-orientation="vertical" class="process-depth-nav">${process.map((p,i)=>`<button role="tab" id="process-tab-${i}" aria-controls="process-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}"><span>${n(i)}</span>${p.name}${arrow}</button>`).join('')}</div><div class="process-depth-panels">${process.map((p,i)=>`<article class="process-depth-panel" role="tabpanel" id="process-panel-${i}" aria-labelledby="process-tab-${i}" tabindex="0" ${i?'hidden':''}><div class="process-depth-art" aria-hidden="true">${industryArt(i)}<strong>${p.name.toUpperCase()}</strong><small>FROM QUESTION TO SOLUTION · ${n(i)} / 05</small></div><div class="process-depth-copy"><span class="eyebrow">STEP ${n(i)} / ${p.name.toUpperCase()}</span><h3>${p.full}</h3><p>${p.text}</p><div class="process-depth-output"><span class="eyebrow">WHAT THIS MOVES YOU TOWARD</span><p>${p.output}</p></div><a class="text-link" href="/approach.html">Explore our approach ${diagonal}</a></div></article>`).join('')}</div></div></div></section>

${domainSection()}

<section id="technology" class="technology-section wrap section">${label('07','THE TECHNOLOGY ECOSYSTEM')}${heading('Built around your needs.<br>Open to the right technology.','We start with your goals, then select the platforms and tools that fit. Deep expertise, without a one-stack mindset.')}<div data-tabs="technology"><div class="tech-tabs" role="tablist" aria-label="Technology categories">${technologies.map((t,i)=>`<button role="tab" id="tech-tab-${i}" aria-controls="tech-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}">${t.name}<span>${n(i)}</span></button>`).join('')}</div>${technologies.map((t,i)=>`<div class="tech-panel" id="tech-panel-${i}" role="tabpanel" aria-labelledby="tech-tab-${i}" tabindex="0" ${i?'hidden':''}><div class="tech-description"><h3>${t.title}</h3><p>${t.text}</p></div><div class="tech-names">${t.items.map(x=>`<span>${x}<b aria-hidden="true">↗</b></span>`).join('')}</div></div>`).join('')}</div></section>

<section id="challenges" class="challenge-section section"><div class="wrap">${label('08','SOLVE WHAT MATTERS')}<div class="challenge-layout"><div><h2>Move beyond<br>the bottleneck.</h2><p>Progress starts with the problems worth solving. We connect each challenge to the engineering it needs.</p><a class="text-link" href="/contact.html">Let’s talk about yours ${arrow}</a></div><div class="challenge-list">${challenges.map((c,i)=>`<details ${i===0?'open':''}><summary><span>${n(i)}</span><h3>${c.name}</h3>${plus}</summary><div class="challenge-body"><p>${c.problem}</p><div class="solution"><span class="eyebrow">THE WAY FORWARD</span><p>${c.solution}</p><span class="solution-tag">${c.tags}</span></div></div></details>`).join('')}</div></div></div></section>

<section id="outcomes" class="outcomes-section section dark-section"><div class="wrap">${label('09','REFERENCE OUTCOMES')}${heading('The impact is<br><em>what matters.</em>','Engineering is the work. Better business outcomes are the reason. Explore published examples of AI in practice.')}<div class="outcome-grid">${outcomes.map((o,i)=>`<article class="outcome"><div class="outcome-top"><span class="eyebrow">${o.sector}</span><span class="eyebrow">${n(i)}</span></div><div class="metric">${o.metric}<span>%</span></div><h3>${o.label}</h3><p>${o.text}</p><span class="outcome-tech">${o.tech}</span></article>`).join('')}</div><p class="outcome-note">Third-party reference outcomes, not Craftertech project claims.</p></div></section>

<section id="work" class="work-section wrap section">${label('10','PROJECT REFERENCES')}${heading('Intelligence, delivered.','Published project references illustrating the engineering possibilities. These examples are not Craftertech engagements.')}<article class="featured-work"><div class="work-visual"><div class="document-sheets" aria-hidden="true"><div class="sheet sheet-back"><span>LEGAL KNOWLEDGE</span><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="sheet sheet-front"><span class="eyebrow">FROM DOCUMENTS TO ANSWERS</span><div class="doc-heading">Clarity.<br>With context.</div><i></i><i></i><i></i><div class="citation"><span class="tiny-mark"></span>TRACEABLE TO THE SOURCE <b>↗</b></div></div></div><div class="work-visual-bottom"><span>LEGAL LINK AI</span><span>DOCUMENT INTELLIGENCE</span></div></div><div class="featured-copy"><span class="eyebrow">LEGALTECH / ARTIFICIAL INTELLIGENCE</span><h3>Legal research,<br>with answers<br> you can trace.</h3><div class="work-result"><strong>4<span>×</span></strong><span>faster legal research<br>with intelligent AI parsing</span></div><p>Complex legal documents become accessible knowledge. AI-powered parsing, conversational research and page-level citations help legal teams find answers with context.</p></div></article><div class="secondary-work"><article class="work-row"><span class="work-thumbnail">${network(1)}</span><div><span class="eyebrow">INSURTECH / ENTERPRISE MODERNIZATION</span><h3>Quikcard. A connected claims lifecycle.</h3><p>From a legacy desktop system to an enterprise health benefits platform.</p></div></article><article class="work-row"><span class="work-thumbnail">${network(5)}</span><div><span class="eyebrow">PUBLIC SECTOR / SOFTWARE ENGINEERING</span><h3>Modernizing election administration.</h3><p>A centralized platform for registration, operations and reporting.</p></div></article></div></section>

<section id="about" class="about-section section"><div class="wrap">${label('11','THE WAY WE WORK')}${heading('Business-led.<br>Engineered end to end.')}<div class="principles"><article><span class="eyebrow">01 / PURPOSE</span><h3>Business first.</h3><p>We begin with your priorities and the impact you need to create. Then we choose the technology that fits.</p></article><article><span class="eyebrow">02 / TRUST</span><h3>Secure by design.</h3><p>Security belongs throughout your systems. We build protection and governance into the engineering process.</p></article><article><span class="eyebrow">03 / OWNERSHIP</span><h3>Connected delivery.</h3><p>From data engineering to MLOps, we support the full AI lifecycle with expertise across every layer.</p></article></div><div class="engagement"><div><span class="eyebrow">BUILT AROUND YOUR ROADMAP</span><h3>A partnership<br>that fits.</h3></div><div class="engagement-list">${engagements.map((e,i)=>`<details ${i===0?'open':''}><summary><h4>${e.name}</h4>${plus}</summary><div><p>${e.text}</p><p class="engagement-fit"><span>IDEAL FOR</span>${e.fit}</p></div></details>`).join('')}</div></div></div></section>

<section id="contact" class="closing-section wrap section">${label('12','YOUR NEXT CHAPTER')}<div class="closing-grid"><h2>Let’s build<br>the future<br><em>with AI.</em></h2><div class="closing-copy"><span class="closing-symbol" aria-hidden="true">↗</span><p>Your business context.<br>Our engineering depth.<br>Let’s see what we can build.</p><a class="button primary" href="/contact.html">Plan your project ${arrow}</a></div></div></section>
</main>
${footer()}
<noscript><style>[role="tablist"]{display:none!important}[role="tabpanel"][hidden]{display:block!important}.cap-story{display:block}.mobile-menu[hidden]{display:flex!important;position:static}.menu-toggle{display:none!important}</style></noscript>
</body></html>`;}
