import {icon} from './icons.js';
export const serviceSlugs=['ai-engineering','application-engineering','cloud-infrastructure','data-analytics','quality-engineering','cybersecurity'];
export const industrySlugs=['healthcare','legaltech','fintech','education','logistics','retail','real-estate','public-sector'];
export const serviceUrl=i=>`/services-${serviceSlugs[i]}.html`;
export const industryUrl=i=>`/industries-${industrySlugs[i]}.html`;
const arrow=icon('north_east');
const link=(url,name,current)=>`<a href="${url}"${current===url?' aria-current="page"':''}>${name}${arrow}</a>`;
export function header(current='/'){
 const entries=[['/','Home'],['/services.html','Services'],['/industries.html','Industries'],['/technology.html','Technology'],['/work.html','Project references'],['/about.html','About Craftertech'],['/approach.html','Our approach'],['/contact.html','Contact']];
 const pageLabel=entries.find(([url])=>url===current)?.[1]||(current.startsWith('/services-')?'Services':current.startsWith('/industries-')?'Industries':'Home');
 return `<header class="site-header floating-header"><a class="header-page-label" href="/">${icon('arrow_forward','label-back')}<span>${pageLabel}</span></a><div class="header-capsule"><div class="capsule-bar"><a class="wordmark" href="/" aria-label="Craftertech home"><img class="brand-symbol" src="/assets/craftertech-white.svg" width="28" height="28" alt=""></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open navigation">${icon('menu','menu-open-icon')}${icon('close','menu-close-icon')}</button></div><nav id="mobile-menu" class="mobile-menu capsule-menu" aria-label="Main navigation" hidden data-lenis-prevent><div class="capsule-links">${entries.map(([url,name])=>link(url,name,current)).join('')}</div><span class="menu-caption">CONNECTED EXPERTISE. REAL POSSIBILITIES.</span></nav></div><a class="contact-link" href="/contact.html">Contact us ${icon('north_east')}</a></header>`;
}
export function footer(){return `<footer class="site-footer"><div class="wrap"><div class="footer-top"><div class="footer-brand"><a class="wordmark" href="/" aria-label="Craftertech home"><img class="brand-symbol" src="/assets/craftertech-white.svg" width="34" height="34" alt=""><span>craftertech</span></a><p>Engineering depth.<br>Intelligent possibilities.</p></div><div><h2>Expertise</h2>${link('/services.html','Services')}${link('/technology.html','Technology')}${link('/approach.html','Our approach')}</div><div><h2>Explore</h2>${link('/industries.html','Industries')}${link('/work.html','Project references')}</div><div><h2>Company</h2>${link('/about.html','About Craftertech')}${link('/contact.html','Contact')}${link('/','Home')}</div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Craftertech. All rights reserved.</span><a href="#top">Back to top ${icon('arrow_upward')}</a></div></div></footer>`}
export function documentPage(title,description,body,path){return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#fafaf8"><script>try{const t=localStorage.getItem('craftertech-theme');document.documentElement.dataset.theme=t||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch(e){}</script><title>${title} — Craftertech</title><meta name="description" content="${description}"><meta property="og:title" content="${title} — Craftertech"><meta property="og:description" content="${description}"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/vendor/lenis.css"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/typography.css"><link rel="stylesheet" href="/pages.css"><script type="module" src="/client.js"></script></head><body id="top"><a class="skip-link" href="#main">Skip to content</a>${header(path)}<main id="main" tabindex="-1">${body}</main>${footer()}</body></html>`}
